### ISSUE TITLE
Settle on MathTransform.Transform method signature

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/ProjNet4GeoAPI#43]
Since #42 `MathTransForm` has the following new public `Transform` function overloads:
* `Transform(ReadonlySpan<double> xs, ReadonlySpan<double> ys, ReadonlySpan<double> zs, Span<double> outXs, Span<double> outYs, Span<double> outZs)`
* `Transform(ReadonlySpan<XY> xys, ReadonlySpan<double> zs, Span<XY> outXys, Span<double> outZs)`
* `Transform(ReadonlySpan<XYZ> xyzs, Span<XYZ> outXyzs)`

`XY` and `XYZ` are tuples of doubles.

For the sake of more flexibility I'd rather go without `XY` and `XYZ` struct. While the case of a vector containing interchanging x- and y-ordinates and an additional z-ordinate vector an be handled efficiently, a case of a vector layout having x-, y, (,z-) and m-ordinate values is not doable without creating vectors and copying ordinate values around.

I propose we change ReadonlySpan<XY> and ReadonlySpan<XYZ> to ReadonlySpan<double> and add `int stepCoord` to the signature or add another overload:

* `Transform(ReadonlySpan<double> xys, int stepCoord, ReadonlySpan<double> zs, int offsetZ, int stepZ, Span<double> outXys, Span<double> outZs)`
* `Transform(ReadonlySpan<double> xyzs, int stepCoord, Span<double> outXys, ReadonlySpan<double> outZs)`

**Comment by airbreather** [comment]
Hmm, I was considering something like [PROJ.4's `proj_trans_generic`](https://proj4.org/development/reference/functions.html#c.proj_trans_generic) method to limit the number of overloads, but ultimately decided against it (at least for the first round) because it felt like that would impact usability in the common case too much to justify (compared to us just having to write more overloads to match the different layouts that the data might come in).

It's along the same lines as this proposal, though, just taken a little further: it's essentially the same as our `xs, ys, zs` overload with a separate `stepCoord` value for each of the three so that all of the vectors can be stored interleaved in one array.

**Comment by FObermaier** [comment]
I wonder of the bulk Transform methods using `[Readonly]Span<T>` are worth it after all:
Here are some benchmarks:

Using @airbreather's SequenceCoordinateConverterBase approach:
```
D:\Development\Source\Repos\ProjNet4GeoAPI\Release\AnyCPU\netcoreapp2.0\TestData\world.wkt
Transformation of 244 geometries using CoordinateArraySequenceFactory with SequenceCoordinateConverterBase took ~125 ms
Transformation of 244 geometries using PackedCoordinateSequenceFactory with SequenceCoordinateConverterBase took ~66 ms
Transformation of 244 geometries using DotSpatialAffineCoordinateSequenceFactory with SequenceCoordinateConverterBase took ~73 ms
```

Using @FObermaier's SequenceTransformer approach:
```
D:\Development\Source\Repos\ProjNet4GeoAPI\Release\AnyCPU\netcoreapp2.0\TestData\world.wkt
Transformation of 244 geometries using CoordinateArraySequenceFactory with SequenceTransformerBase took ~94 ms
Transformation of 244 geometries using CoordinateArraySequenceFactory with CoordinateArraySequenceTransformer took ~112 ms
Transformation of 244 geometries using PackedCoordinateSequenceFactory with SequenceTransformerBase took ~50 ms
Transformation of 244 geometries using PackedCoordinateSequenceFactory with PackedDoubleSequenceTransformer took ~47 ms
Transformation of 244 geometries using DotSpatialAffineCoordinateSequenceFactory with SequenceTransformerBase took ~47 ms
Transformation of 244 geometries using DotSpatialAffineCoordinateSequenceFactory with DotSpatialSequenceTransformer took ~45 ms
```

Note: 
* `SequenceTransformerBase` follows a naive approach without any tweaks by using `ICoordinateSequence.[Get|Set]Ordinate`.
* The specialized Transformer classes (attempt) to take benefit of the knowledge of its memory layout. but the benefit is next to none. 

See 2b0100f3

**Comment by FObermaier** [comment]
Without the `(Readonly)Span<T>` fluff, the performance measures are similar to those using `SequenceTransformerBase`

```
D:\Development\Source\Repos\ProjNet4GeoAPI\Release\AnyCPU\netcoreapp2.0\TestData\world.wkt
Transformation of 244 geometries using CoordinateArraySequenceFactory with no span took ~98 ms
Transformation of 244 geometries using PackedCoordinateSequenceFactory with no span took ~49 ms
Transformation of 244 geometries using DotSpatialAffineCoordinateSequenceFactory with no span took ~47 ms
```
See 4790d5d6

**Comment by FObermaier** [comment]
Note: Here are the numbers for the same tests and ProjNet v1.4.1:
```
D:\Development\Source\Repos\ProjNet4GeoAPI\ProjNet.Comparison\bin\Release\TestData\world.wkt
Transformation of 244 geometries using CoordinateArraySequenceFactory with no span took ~137 ms
Transformation of 244 geometries using PackedCoordinateSequenceFactory with no span took ~84 ms
Transformation of 244 geometries using DotSpatialAffineCoordinateSequenceFactory with no span took ~84 ms
```

Sequence | v1.4.1 | v2.0 | ratio | improvement
-- | -- | -- | -- | --
CoordinateArraySequence | 137 | 98 | 71.5% | 28.5%
PackedDoubleCoordinate | 84 | 49 | 58.3% | 41.7%
DotSpatialAffineCoordinate | 84 | 47 | 56.0% | 44.0%

**Comment by airbreather** [comment]
`netcoreapp2.0` doesn't use an optimized version of `Span<T>`.  `netcoreapp2.1` does, and I think `netcoreapp2.2` had several JIT improvements on top of that.

[BenchmarkDotNet](https://benchmarkdotnet.org/) is the standard for benchmarking.  It runs the code in isolation, warms up the JIT, does its own looping (making sure to do enough iterations that the result is statistically significant), offers a memory diagnoser to see how much a particular solution allocates (which can be relevant when the system is under load), and probably solves other problems I don't even know about because everybody who seems to know the details about how to reliably run benchmarks on .NET code says to just use BenchmarkDotNet.

We should probably deal with Z differently instead of allocating it on-the-fly if it's not there, **at least** in cases where `DimSource` is 2 and so we know that the transform implementation won't use it... my thought:
- sequence-to-span converter: if the input sequence doesn't have Z, then regardless of `DimSource`,
    - if we're targeting `ReadOnlySpan<double> zs`, yield a 0-length span
    - if we're targeting `ReadOnlySpan<XYZ> xyzs`, fill the gaps with 0s
- transform implementations: if the converter gave us a 0-length span for Z,
    - if `DimSource` is 2, pass through the 0-length span for consumers to essentially ignore
    - if `DimSource` is 3, then I see two decent options:
        - throw, or
        - still pass it through, and have consumers treat this as a full-length span of zeroes

I ran [these benchmarks](https://github.com/airbreather/AirBreather.Projections/blob/master/README.md) a while back to get an idea of whether or not it's worth trying to optimize.  At the time, the answer was yes, and there seemed to be tangible benefits at every incremental step (with the SoA memory layout, that is).  According to that table:
1. Simply inlining the calculation and constants, removing the allocations, and reordering the instructions shaved off about 50% of the time from ProjNet 1.x.
    - I suspect that what we already have in our perf branches will give us much of this improvement.
1. Unrolling the loop by 4 shaved off about 17% of the remaining time.
1. Moving the same unrolled code to a native project compiled using Intel's C++ compiler shaved off about 34% of the remaining time.
1. Replacing the manually unrolled version with a version that used AVX2 and Intel's intrinsics shaved off a further 38% of the remaining time.

Together, the AVX2 solution shaved off about 67% of the time it takes to run something resembling the best that the JIT could possibly theoretically do if we stored the data in `xs, ys, zs` format.

If there's dispute over something in my own benchmark, I can update it to help shine light into that.  In fact, it was run back when `netcoreapp2.0` was state-of-the-art, so I should probably update it for `netcoreapp2.2` regardless.  My free trial of the Intel C++ compiler has run out, so unfortunately I can't make changes to the native parts (I do still have the compiled DLLs to run the existing native paths).

**Comment by airbreather** [comment]
> In fact, it was run back when `netcoreapp2.0` was state-of-the-art, so I should probably update it for `netcoreapp2.2` regardless.

Pushed an update.  The overall picture [stayed the same](https://github.com/airbreather/AirBreather.Projections/blob/54b698fb857bf0568b8597a98c4fedb389204501/README.md), just some details changed: unrolling by hand is still better than doing nothing, and AVX2 is still better than all the other scalar-only code.

**Comment by FObermaier** [comment]
Ok, BenchmarkDotNet to the rescue.

I did use `netcoreapp 2.1`:

```
// Benchmark Process Environment Information:
// Runtime=.NET Core 2.1.7 (CoreCLR 4.6.27129.04, CoreFX 4.6.27129.04), 64bit RyuJIT
// GC=Concurrent Workstation
// Job: DefaultJob
```

With no optimization of `[ReadOnly]Span<T>`:

| Method |    Mean |    Error |   StdDev | Ratio | Output |
| -- | -------- | -- | -- | -- | -- |
|  TestCoordinateArraySequence | 4.823 s | 0.0431 s | 0.0360 s |  1.00 | ~85ms |
|     TestPackedDoubleSequence | 2.629 s | 0.0406 s | 0.0360 s |  0.55 | ~43ms |
| TestDotSpatialAffineSequence | 2.721 s | 0.0219 s | 0.0183 s |  0.56 | ~44ms |

With `SequenceTransformer`:

|  Method |    Mean |    Error |   StdDev | Ratio | Output |
| -- | -------- | -- | -- | -- | -- |
|     TestCoordinateArraySequence | 4.832 s | 0.0390 s | 0.0365 s |  1.00 | ~86ms |
|  TestCoordinateArraySequenceOpt | 5.550 s | 0.0347 s | 0.0290 s |  1.15 | ~100ms |
|        TestPackedDoubleSequence | 2.758 s | 0.0272 s | 0.0254 s |  0.57 | ~45ms |
|     TestPackedDoubleSequenceOpt | 2.342 s | 0.0263 s | 0.0246 s |  0.48 | ~37ms |
|    TestDotSpatialAffineSequence | 2.737 s | 0.0182 s | 0.0162 s |  0.57 | ~46ms |
| TestDotSpatialAffineSequenceOpt | 2.422 s | 0.0203 s | 0.0170 s |  0.50 | ~38ms |

Ergo, there is some improvement, but is it worth it?

**Comment by FObermaier** [comment]
> if DimSource is 3, then I see two decent options:
> * throw, or
> *still pass it through, and have consumers treat this as a full-length span of zeroes

As soon as you have a `GeocentricTransform` you are required to have valid z/altitude values.

**Comment by airbreather** [comment]
> Ergo, there is some improvement, but is it worth it?

What does it look like when you run using these flags?
https://github.com/airbreather/AirBreather.Projections/blob/54b698fb857bf0568b8597a98c4fedb389204501/AirBreather.Projections/Program.cs#L15-L19

**Comment by FObermaier** [comment]
```
// Benchmark Process Environment Information:
// Runtime=.NET Core 2.1.7 (CoreCLR 4.6.27129.04, CoreFX 4.6.27129.04), 64bit RyuJIT
// GC=Concurrent Server
// Job: Job-MOAZGJ(Server=True)
```
With no optimization of `[ReadOnly]Span<T>`:

|                       Method |    Mean |    Error |   StdDev | Ratio | RatioSD | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|----------------------------- |--------:|---------:|---------:|------:|--------:|------------:|------------:|------------:|--------------------:|
|  TestCoordinateArraySequence | 2.626 s | 0.0525 s | 0.0539 s |  1.00 |    0.00 |   6000.0000 |   3000.0000 |   1000.0000 |           1172.7 MB |
|     TestPackedDoubleSequence | 2.138 s | 0.0318 s | 0.0297 s |  0.82 |    0.02 |   7000.0000 |   6000.0000 |   5000.0000 |           756.81 MB |
| TestDotSpatialAffineSequence | 2.128 s | 0.0269 s | 0.0238 s |  0.81 |    0.02 |   5000.0000 |   4000.0000 |   4000.0000 |           781.33 MB |


With `SequenceTransformer`:

|                          Method |    Mean |    Error |   StdDev | Ratio | RatioSD | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------------------------- |--------:|---------:|---------:|------:|--------:|------------:|------------:|------------:|--------------------:|
|     TestCoordinateArraySequence | 2.539 s | 0.0175 s | 0.0155 s |  1.00 |    0.00 |   9000.0000 |   4000.0000 |   1000.0000 |           1172.7 MB |
|  TestCoordinateArraySequenceOpt | 2.426 s | 0.0507 s | 0.0449 s |  0.96 |    0.02 |  15000.0000 |  10000.0000 |   5000.0000 |          1620.64 MB |
|        TestPackedDoubleSequence | 2.104 s | 0.0152 s | 0.0143 s |  0.83 |    0.01 |  10000.0000 |   9000.0000 |   6000.0000 |            756.8 MB |
|     TestPackedDoubleSequenceOpt | 1.802 s | 0.0145 s | 0.0136 s |  0.71 |    0.01 |  10000.0000 |   9000.0000 |   6000.0000 |            756.8 MB |
|    TestDotSpatialAffineSequence | 2.095 s | 0.0138 s | 0.0122 s |  0.83 |    0.01 |   8000.0000 |   6000.0000 |   3000.0000 |           781.33 MB |
| TestDotSpatialAffineSequenceOpt | 1.783 s | 0.0190 s | 0.0158 s |  0.70 |    0.01 |   7000.0000 |   5000.0000 |   3000.0000 |           781.32 MB |

**Comment by FObermaier** [comment]
```
// Benchmark Process Environment Information:
// Runtime=.NET Core 2.2.2 (CoreCLR 4.6.27317.07, CoreFX 4.6.27318.02), 64bit RyuJIT
// GC=Concurrent Server
// Job: Job-PROIUN(Server=True)
```

With no optimization of `[ReadOnly]Span<T>`:

|                       Method |    Mean |    Error |   StdDev | Ratio | RatioSD | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|----------------------------- |--------:|---------:|---------:|------:|--------:|------------:|------------:|------------:|--------------------:|
|  TestCoordinateArraySequence | 2.636 s | 0.0334 s | 0.0312 s |  1.00 |    0.00 |   3000.0000 |   1000.0000 |           - |          1172.69 MB |
|     TestPackedDoubleSequence | 2.177 s | 0.0429 s | 0.0477 s |  0.83 |    0.02 |   9000.0000 |   8000.0000 |   6000.0000 |            756.8 MB |
| TestDotSpatialAffineSequence | 2.208 s | 0.0438 s | 0.0504 s |  0.84 |    0.02 |   6000.0000 |   5000.0000 |   3000.0000 |           781.33 MB |

Ergo: No further improvement.

With `SequenceTransformer`:

has to wait till later.

**Comment by FObermaier** [comment]
Explanation of what the test procedure in question does:
1. Loads some 244 Polygons, of varying size, with or without holes, into memory, 
2. Creates a coordinate transformation WGS84 to WebMercator
3. In a loop from 0 to <=50 transforms all 244 polygons.
  Inside the loop, a `Stopwatch` measures the time for transforming all 244 polygons and adds it up after the first iteration. As a result the average time per iteration is written to console.

So as a result for transforming 12.000 geometries the `[Readonly]Span<T>` offer a benefit of 0.5s.
The fastest implementations are `PackedCoordinateSequence` with its transformer and `DotSpatialAffineCoordinateSequence` with its transformer both performig a cycle at ~27ms whereas the implementation for those without an optimization attempt take ~34ms.

**Comment by airbreather** [comment]
updated [`perf/span-tweaks`](https://github.com/NetTopologySuite/ProjNet4GeoAPI/tree/perf/span-tweaks) branch... I'm heading out the door now, not much time to type out a more detailed message but see message on the latest commit for what was changed.

note that I didn't bother making sequence-aware optimizations for `CoordinateArraySequence`, so that line will look worse than it theoretically could be.

latest run I did:
``` ini

BenchmarkDotNet=v0.11.4, OS=Windows 10.0.17134.648 (1803/April2018Update/Redstone4)
Intel Core i7-6850K CPU 3.60GHz (Skylake), 1 CPU, 12 logical and 6 physical cores
Frequency=3515619 Hz, Resolution=284.4449 ns, Timer=TSC
.NET Core SDK=2.2.201
  [Host]     : .NET Core 2.2.2 (CoreCLR 4.6.27317.07, CoreFX 4.6.27318.02), 64bit RyuJIT
  Job-KTHWZF : .NET Core 2.2.2 (CoreCLR 4.6.27317.07, CoreFX 4.6.27318.02), 64bit RyuJIT

Server=True  

```
|                            Method |      SequenceFactory |       Implementation |      Mean |     Error |    StdDev | Ratio | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|---------------------------------- |--------------------- |--------------------- |----------:|----------:|----------:|------:|------------:|------------:|------------:|--------------------:|
|                        **RunDefault** | **Coord(...)ctory [30]** | **Seque(...)erter [27]** | **11.635 ms** | **0.0234 ms** | **0.0183 ms** |  **1.00** |           **-** |           **-** |           **-** |          **1258.09 KB** |
| RunWithSequenceAwareOptimizations | Coord(...)ctory [30] | Seque(...)erter [27] | 11.922 ms | 0.0252 ms | 0.0223 ms |  1.02 |           - |           - |           - |          1258.09 KB |
|                                   |                      |                      |           |           |           |       |             |             |             |                     |
|                        **RunDefault** | **Coord(...)ctory [30]** |  **SequenceTransformer** | **10.931 ms** | **0.0283 ms** | **0.0251 ms** |  **1.00** |           **-** |           **-** |           **-** |           **209.61 KB** |
| RunWithSequenceAwareOptimizations | Coord(...)ctory [30] |  SequenceTransformer |  7.391 ms | 0.0257 ms | 0.0228 ms |  0.68 |           - |           - |           - |           419.28 KB |
|                                   |                      |                      |           |           |           |       |             |             |             |                     |
|                        **RunDefault** | **DotSp(...)ctory [41]** | **Seque(...)erter [27]** | **11.802 ms** | **0.0364 ms** | **0.0340 ms** |  **1.00** |           **-** |           **-** |           **-** |          **1258.09 KB** |
| RunWithSequenceAwareOptimizations | DotSp(...)ctory [41] | Seque(...)erter [27] |  4.860 ms | 0.0140 ms | 0.0124 ms |  0.41 |           - |           - |           - |           209.62 KB |
|                                   |                      |                      |           |           |           |       |             |             |             |                     |
|                        **RunDefault** | **DotSp(...)ctory [41]** |  **SequenceTransformer** | **10.958 ms** | **0.0354 ms** | **0.0314 ms** |  **1.00** |           **-** |           **-** |           **-** |           **209.61 KB** |
| RunWithSequenceAwareOptimizations | DotSp(...)ctory [41] |  SequenceTransformer |  4.499 ms | 0.0153 ms | 0.0143 ms |  0.41 |           - |           - |           - |           209.59 KB |
|                                   |                      |                      |           |           |           |       |             |             |             |                     |
|                        **RunDefault** | **Packe(...)ctory [31]** | **Seque(...)erter [27]** | **11.433 ms** | **0.0192 ms** | **0.0170 ms** |  **1.00** |           **-** |           **-** |           **-** |          **1258.09 KB** |
| RunWithSequenceAwareOptimizations | Packe(...)ctory [31] | Seque(...)erter [27] |  4.767 ms | 0.0079 ms | 0.0066 ms |  0.42 |           - |           - |           - |           209.62 KB |
|                                   |                      |                      |           |           |           |       |             |             |             |                     |
|                        **RunDefault** | **Packe(...)ctory [31]** |  **SequenceTransformer** | **11.126 ms** | **0.0246 ms** | **0.0219 ms** |  **1.00** |           **-** |           **-** |           **-** |           **209.61 KB** |
| RunWithSequenceAwareOptimizations | Packe(...)ctory [31] |  SequenceTransformer |  4.460 ms | 0.0089 ms | 0.0074 ms |  0.40 |           - |           - |           - |           209.59 KB |

**Comment by FObermaier** [comment]
@airbreather , nice work.

I suggest we go for just one overloadable `TransformCore` method using spans and direct the others to it. (faciliated [PROJ.4's `proj_trans_generic`](https://proj4.org/development/reference/functions.html#c.proj_trans_generic))

```C#
protected virtual TransformCore(
  // input
  ReadonlySpan<double> xs, ReadonlySpan<double> ys, ReadonlySpan<double> zs,
  // output
  ReadonlySpan<double> xs, ReadonlySpan<double> ys, ReadonlySpan<double> zs,
  // strides
  int strideX = 1, int strideY = 1, intStrideZ = 1
  /*
  // maybe offsets
  int offsetX = 0, int offsetY = 1, intOffsetZ = 2 
   */
) 
```

**Comment by airbreather** [comment]
> I suggest we go for just one overloadable `TransformCore` method using spans and direct the others to it. (faciliated [PROJ.4's `proj_trans_generic`](https://proj4.org/development/reference/functions.html#c.proj_trans_generic))

OK.  It's not my favorite, but on balance, I'm still very happy with it (with some **very** minor surface-level tweaks, see the bottom of this comment).  For posterity, here's what I considered before saying that:

## Bad Things

- All subclasses **must** override a very awkward method (seems easy to write bugs).
- "One-by-one" transformations look like they'll have a higher overhead **compared** to the other solutions that have been proposed so far on this thread (probably still better than what we have today).
- A little bit complicated to detect when a particular layout-restricted optimization is valid, because you have to test weird stuff about the parameter values instead of having it spoon-fed to you.

## Good Things

- Fully solves the problem without requiring any GC allocations or (when the layout is known) copying.
- Offers the most flexibility for implementations who aren't afraid of getting their hands dirty.
- Even the boring in-the-box implementations (when implemented correctly) should tend to outperform the implementations from any other solution that's been seriously considered on this thread... I'm not particularly interested in verifying this claim, but it's hard to imagine it being bad.

## Minor details
Just surface-level edits to names and types:
```csharp
protected virtual TransformCore(
    // input
    ReadOnlySpan<double> inXs, ReadOnlySpan<double> inYs, ReadOnlySpan<double> inZs,
    // output
    Span<double> outXs, Span<double> outYs, Span<double> outZs,
    // strides
    int strideX = 1, int strideY = 1, int strideZ = 1
)
```

> // maybe offsets

overkill because you can get the same behavior by passing in `theSpanToOffset.Slice(theOffset)`

**Comment by FObermaier** [comment]
Just to be clear, I just want one overload that __uses spans__. I think having to override one that is a little awkward is better than having to override three.

Why would it hurt "one-by-one" transformations?

**Comment by airbreather** [comment]
Ahh, so it would be something like:
```csharp
protected abstract (double x, double y, double z) TransformCore(double x, double y, double z);
protected virtual void TransformCore(/* all the span / stride parameters */)
{
    // call TransformCore
}
```

OK, that scratches off my first "bad thing" and my last "good thing" bullet points.  I'm still very happy with it.

> Why would it hurt "one-by-one" transformations?

It won't, if my new understanding is correct.  The reason why I **thought** so was because I had thought that the idea was to send all one-by-one methods through the span method.

To clarify why that situation made me say that, it was because I had this picture in my head:
```csharp
public (double x, double y, double z) Transform(double x, double y, double z)
{
    Span<double> xs = stackalloc double[] { x };
    Span<double> ys = stackalloc double[] { y };
    Span<double> zs = stackalloc double[] { z };
    TransformCore(xs, ys, zs,
                  xs, ys, zs,
                  1,  1,  1);
    return (xs[0], ys[0], zs[0]);
}
```
The extra call with a lot of parameters, plus all the stuff it has to write to the "stack" (though some surely gets enregistered), is a cost that doesn't exist when "one-by-one" is the fundamental method.
